### ISSUE TITLE
android app no longer functional

### ISSUE THREAD

**Issue by nvsio** [AbstractedSheep/Shuttle-Tracker#11]
It seems this application is using a deprecated data feed that is no longer active and supported. Please contact the RCOS mailing list if you are interested in implementing an update that takes advantage of the feeds being scraped by the [RPI Mobile](https://github.com/rpi-mobile) group. 

![menu](https://f.cloud.github.com/assets/1820040/2265505/a849a10c-9e82-11e3-99bb-5c8be7250202.png)
![home](https://f.cloud.github.com/assets/1820040/2265506/a84b065a-9e82-11e3-8a6a-f796e548b6aa.png)

**Comment by kench** [comment]
Some background: This Android app relies on a service hosted by AbstractedSheep to scape the JSON data feeds from shuttles.rpi.edu.

Unfortunately, it went down sometime in the last year and hasn't worked since.

Ideally, the app should be updated to pull directly from shuttles.rpi.edu itself.

**Comment by brendonjustin** [comment]
The Android app is, I think, unlikely to be updated by the original author. If someone updates it and makes a pull request, I could probably get the app on Google Play updated.

The iOS app avoids this issue by only showing routes and shuttle locations on the map, so as to rely only on shuttles.rpi.edu.

**Comment by kench** [comment]
> Please contact the RCOS mailing list if you are interested in implementing an update that takes advantage of the feeds being scraped by the RPI Mobile group.

@nikhilsrinivasan, I hope you don't mean scraping and republishing the shuttle location data for use with mobile apps.  Creating an additional dependency on a service that merely acts as a proxy for shuttles.rpi.edu is a _very bad idea_ and is the reason why this app is broken.

**Comment by nvsio** [comment]
I actually wasn't aware if we had completely moved away from persisting shuttle data internally – this hopefully isn't the case anymore.

Shuttle Track is actually maintained by the [Web Technologies Group](https://github.com/wtg/shuttle_tracking/) – as @kench mentions it is best to aggravate feeds from their service directly. It would probably be wise to contact them regarding proper use of their feeds before publishing an updated app to the store.
