### ISSUE TITLE
Data Service returning empty data

### ISSUE THREAD

**Issue by stephensilber** [AbstractedSheep/Shuttle-Tracker#9]
http://shuttles.abstractedsheep.com/data_service.php is returning empty json responses as far as I can tell when trying to call for current shuttle locations and etas

**Comment by brendonjustin** [comment]
Thanks for the report.  Our shuttle tracker code has sort of been in limbo since we graduated, but we are slowly working on a solution.  For the iOS app, I'm switching back to shuttles.rpi.edu (http://shuttles.rpi.edu/vehicles/current.js) for shuttle locations until we get another solution going.

**Comment by kench** [comment]
Why wasn't the app pulling data from shuttles.rpi.edu in the first place?

**Comment by kench** [comment]
Just an update.  A member of the Web Technologies Group is working on getting mobile application fixed and removing any dependencies on any web services other than shuttles.rpi.edu.

**Comment by brendonjustin** [comment]
I already implemented the switch back earlier this week, in my local repo. I just need to test it while the shuttles are running.  Work hours and being in a different time zone are not conducive for testing.

**Comment by stephensilber** [comment]
any further updates on whether the switch that was implemented is functioning?

**Comment by kench** [comment]
Looking at the repo, it hasn't been committed yet.

**Comment by brendonjustin** [comment]
It is in the ios_wip branch. The dev center has been down intermittently which has held up submission of an updated app. I merge to master every release or sooner if I am not planning another release soon.

**Comment by kench** [comment]
The WTG can test builds of this app.  Email me if you're interested.

**Comment by brendonjustin** [comment]
Switched to shuttles.rpi.edu for the foreseeable future.

**Comment by kench** [comment]
Thank you for closing this bug.  I'm working on a JSON data format for schedules at the moment, I'll provide you with the endpoint + data once it's complete.
